<?php

/**
* Implements hook_form_alter().
* 
* Make some adjustments to the way revisioning options appear when editing.
*/
function revisioning_display_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#node_edit_form']) && !empty($form['revision_information'])) {
    // Remove revision options from vertical tabs, and move to top of page.
    //unset($form['revision_information']['#group']);
    //$form['revision_information']['#weight'] = -10;
    //$form['revision_information']['#collapsed'] = FALSE;
    // Do the same for publishing options to keep close to revisioning options
    //unset($form['options']['#group']);
    //$form['options']['#weight'] = -8;
    //$form['options']['#collapsed'] = FALSE;
    
    // For admins and power editors adjust details for options
    if (!empty($form['revision_information']['revision_operation']) && user_access('administer nodes')) {
      if ($form['nid']['#value']) { // The node exists
        // Set defaults
        $form['revision_information']['revision_operation']['#default_value'] = 1;
      }
      else { // The node is being created
        // Get rid of log option when creating new content
        unset($form['revision_information']['log']);
        // Set defaults
        $form['revision_information']['revision_operation']['#default_value'] = 2;
      }     
    }
    //dpm($form);
  }
}
